# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180714_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_url',
            field=models.URLField(unique=True),
        ),
    ]
